language: node_js
node_js:
- node
- '6'
notifications:
  slack:
    secure: dHICK5vGCk8QsJBKb1IOpf/sHDJATeqA1ljwwPKJtMnPmDRJEhSgPaA8bUkPG6GczZS9ak599dxy79hBHP69n4KL66VkO0sw9tVUT4cOOonpWiHD4bN7K+hUxe8156wiY2xi00dRNNabTZVkRp41EOLA/byHNFm4VxB3Bnl058/BeHpp+EDNxC4KuOtBi1iTkLq3/g2OHqOwP2jHNJalPWbFMyjeLjvgbjVTl0NJnpmzKruj4M0qLLTg8+RoZzBeRBFEj89HEdhIVGSClCzIXQpbEWib1s/ahto3JE3iMCkU60ysOe5VZogR86vk8lXls4owV2AoO5UtCwlG+RVdZbpSYpDaPwPglEAzcxeAvePUnCVQLUgxmkStgyOmnP7LQ6NaVKfG09VSIgcyiv9YpoRd5V+xjlSh1FjOvz83SteRWzZsJu9Iyu4Evtsla1vgFJiMHCLwBo4M9RwsIHXeWdRjmUf9SWq3UV0p6y1CVXMxr2OcJxIXxyFNqLefMy8Na6F1UMN7ChfpExPylXjV6HQUQtkvnKuzJy4qG3m0KzwPONgfDAYcFUbEKDGaafs7JZsn6iXxJ7Uk2xiBOS4e9DZN1wg+idhW2gXfqreOLM6IiXFu1LIwVqz7jaO0M1xTelumE86jZ0dQ+eH+3f61KiCfkRehD8CbX5MOGzEZups=
